# SPDX-License-Identifier: LGPL-3.0-only

name: Check formatting

on:
  push:

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: true

    - run: pdm install -Gformat
    - run: pdm run yapf_check
